export const PostAdApi = {
  uploadImage: "/product/v1/image/upload",
  previewProduct: "/product/v1/preview",
  intermediatePreview: "/product/v1/intermediate/preview",
  finalPreview: "/product/v1/final/preview",
  profile: "/user/me",
  createProduct: "/product/v1/create",
  Image: "/product/image/url",
  categories: "/category/all",
  subcategories: "/subcategory/all",
  divisions: "/division/all",
  divisionBySubcategory: "/division/view",
  getLocationHighlights: "/product/v1/getlocationhighlights",
  brandsBySubcategory: "/brand/getbrandsbysubcategoryid",
  modelsByBrand: "/model/brand",
};
